### ISSUE TITLE
[bug] GitHub pages deployment gives 404 error 

### ISSUE THREAD

**Issue by rajpiskala** [jamesturton/bose-qc35-usb-c#1]
![image](https://user-images.githubusercontent.com/57082175/153692231-a9dda721-26c8-420f-9903-d3df97dd8b82.png)

Accessing the GitHub pages deployment gives an error saying that there isn't a web page here. I believe it's because there isn't an `index.html` page in the `main` branch. The only html files I can find are in the bom folder, so it might be better to deploy those separately on a `gh-pages` branch or create an `index.html` that loads those files in. Could it be related to that?

**Comment by jamesturton** [comment]
Oops! I didn't mean to create a GitHub pages deployment. That should now be fixed.
