### ISSUE TITLE
[feature] Add a README to the project

### ISSUE THREAD

**Issue by rajpiskala** [jamesturton/bose-qc35-usb-c#2]
I've been reading through the codebase and I'm having trouble understanding how to use all of the files. Is there a README or webpage (e.g. an article or blogpost) that outlines how I can recreate this mod as well? Looking to mod my QC35, so this would be very useful to have, thanks and I can help with the README if needed!

**Comment by jamesturton** [comment]
Hi @RogueArt! I have now added a README to the repo. Let me know if still have any more questions regarding this.
