### ISSUE TITLE
Missing values for R1, R2, R3, R4, R17, R18, R19

### ISSUE THREAD

**Issue by Casperdroid5** [jamesturton/bose-qc35-usb-c#4]
dear jamesturton, the values for R1, R2, R3, R4, R17, R18, R19 are missing. could you please tell me what values they are supposed to be?

**Comment by Casperdroid5** [comment]
oh i see now! you are not using those pads...

**Comment by jamesturton** [comment]
I left them not mounted. If you wanted to be safe then they should be protection diodes `CG0402MLC-05LG`
