### ISSUE TITLE
Question about buying parts

### ISSUE THREAD

**Issue by ZasoZ** [jamesturton/bose-qc35-usb-c#5]
Hi I thought this was a really cool project but I was wondering if you knew any stores that sells all the parts and ships to Sweden ?

Kind regards

**Comment by Agnus-Castus** [comment]
https://www.mouser.se or https://www.digikey.se/en

**Comment by amomchilov** [comment]
@jamesturton Does anything prevent us from just scrapping the original board for parts, and transplanting them over?

**Comment by jamesturton** [comment]
> @jamesturton Does anything prevent us from just scrapping the original board for parts, and transplanting them over?

You can absolutely do this! I tried to layout the circuit board with the components in the same place to make it easier when moving them across. The only thing to note is that you will need the two 5k1 resistors which are required by the USB spec for USB gen2 when using USB type-C. And the new USB type-C port of course!

**Comment by jonas-stg** [comment]
Maybe someone could provide direct links for parts?
I don't know how to search for some of them, or could give me an example for 
![image](https://github.com/jamesturton/bose-qc35-usb-c/assets/139757008/832be0d9-df1b-4434-9740-35a74e6b823a)
