### ISSUE TITLE
Is this 4 layer pcb?

### ISSUE THREAD

**Issue by galvakojis** [jamesturton/bose-qc35-usb-c#6]
Well look like this is a 4 layer pcb? Maybe any suggestions where I could manufacture it at less price?

**Comment by jamesturton** [comment]
Yes, this is a 4 layer PCB. I have had boards made at [JLCPCB ](https://jlcpcb.com/) before (very cheap for the board, but the shipping and import taxes can be very expensive depending on where you live). If you are in Europe, I would also recommend looking at [AISLER](https://aisler.net/) as they offer free shipping and quick delivery within the EU.
