### ISSUE TITLE
Does this work with QC35 II's?

### ISSUE THREAD

**Issue by DerZade** [jamesturton/bose-qc35-usb-c#7]
In all files it says QC35, but not QC35 **II**.
Does this mod work for QC35 II as well?

**Comment by jamesturton** [comment]
Very good question! I don't actually know as I don't have the QC35 II's, so not sure if they changed the design of the board at all, but from what I can see, the right ear cup looks identical between I and II so I think it should work. My wife actually has a pair of the QC35 II's so I could try opening them while she is sleeping some time :laughing:

**Comment by DerZade** [comment]
That would be amazing 🙈 There was a guy on reddit who apparently uses this mod with II's, but I'm not 100% sure. I'll probably PM him and ask to clarify.

**Comment by DerZade** [comment]
[According to him](https://www.reddit.com/r/bose/comments/qvn1d7/qc35_ii_with_usb_c/jdd1oe6?context=3) the PCBs are interchangeable between Version I and II.

Hope he's trustworthy 😂

**Comment by jamesturton** [comment]
Great, thanks for the update! 🙂 I shall update the readme

**Comment by jamesturton** [comment]
Fixed in  7100c0c!
